baseURL = 'https://phinjensen.com/'
languageCode = 'en-us'
title = 'Phineas Jensen'
copyright = 'Â© 2021-{year} Phineas Jensen â€” Made with ğŸ˜± in Provo, UT'
[params]
  author = 'Phineas Jensen'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
